### ISSUE TITLE
Tool doesn't run when initiated from outside the tool directory

### ISSUE THREAD

**Issue by 0xgb** [0xNanda/Oralyzer#8]
After the recent update, the tool throws some error when you try to run from outside the tool directory.

```
▶ python3 Oralyzer/oralyzer.py -h
   ____           __
  / __ \_______ _/ /_ _____ ___ ____
 / /_/ / __/ _ `/ / // /_ // -_) __/
 \____/_/  \_,_/_/\_, //__/\__/_/
                 /___/

Traceback (most recent call last):
  File "Oralyzer/oralyzer.py", line 13, in <module>
    from core.wayback import get_urls
  File "/Users/gaurangbhatnagar/Flow-Tools/Oralyzer/core/wayback.py", line 2, in <module>
    from core.others import good,bad,info
  File "/Users/gaurangbhatnagar/Flow-Tools/Oralyzer/core/others.py", line 19, in <module>
    with open('core/config.json', 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'core/config.json'
```

This only works when you navigate to the folder and run the tool.

```
▶ cd Oralyzer
▶ python3 oralyzer.py -h
   ____           __
  / __ \_______ _/ /_ _____ ___ ____
 / /_/ / __/ _ `/ / // /_ // -_) __/
 \____/_/  \_,_/_/\_, //__/\__/_/
                 /___/

usage: oralyzer.py [-h] [-u URL] [-l PATH] [-crlf] [-p PAYLOAD] [--proxy] [--wayback]

optional arguments:
  -h, --help            show this help message and exit
  -u URL, --url URL     scan single target
  -l PATH, --list PATH  scan multiple target
  -crlf                 scan for CRLF Injection
  -p PAYLOAD, --payload PAYLOAD
                        use payloads from a file
  --proxy               use proxy
  --wayback             fetch URLs from archive.org
```

**Comment by 0xNanda** [comment]
The issue has been fixed, thanks for reporting!

**Comment by 0xgb** [comment]
@0xNanda 

This looks like a partial fix. 

It works for the example highlighted above (`python3 Oralyzer/oralyzer.py -h`)

But still doesn't work if you are running command from the home directory (`python3 /Users/<username>/Tools/Oralyzer/oralyzer.py -h`)
